{% set name = "rpyc" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomerfiliba-org/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 45a5d237490b6b48cad625c0f8be877d260ea35a6646d0227e1e46f868da8848

build:
  noarch: python
  number: 1
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - plumbum

test:
  imports:
    - rpyc
    - rpyc.core
    - rpyc.lib
    - rpyc.utils
  commands:
    - pip check
    - rpyc_classic --help
    - rpyc_registry --help
    - rpyc_classic.py --help
    - rpyc_registry.py --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tomerfiliba-org/rpyc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparent, Symmetric Distributed Computing

  description: |
    RPyC (pronounced like are-pie-see), or Remote Python Call, is a
    transparent library for symmetrical remote procedure calls,
    clustering, and distributed-computing. RPyC makes use of
    object-proxying, a technique that employs python's dynamic nature, to
    overcome the physical boundaries between processes and computers, so
    that remote objects can be manipulated as if they were local.
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/tomerfiliba-org/rpyc

extra:
  recipe-maintainers:
    - mtsolmn
    - comrumino
    - jacobfeder
