{% set name = "rpyc" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomerfiliba-org/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3492e83d7dd67011a9215612c13d92f52e96a0690fc7bbaea4b3ead1e9de5517

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - plumbum

test:
  imports:
    - rpyc
    - rpyc.core
    - rpyc.lib
    - rpyc.utils
    - rpyc.tests
  commands:
    - pip check
    - rpyc_classic --help
    - rpyc_registry --help
    - rpyc_classic.py --help
    - rpyc_registry.py --help
    - python tests/test_classic.py
  requires:
    - pip

about:
  home: https://github.com/tomerfiliba-org/rpyc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparent, Symmetric Distributed Computing

  description: |
    RPyC (pronounced like are-pie-see), or Remote Python Call, is a
    transparent library for symmetrical remote procedure calls,
    clustering, and distributed-computing. RPyC makes use of
    object-proxying, a technique that employs python's dynamic nature, to
    overcome the physical boundaries between processes and computers, so
    that remote objects can be manipulated as if they were local.
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/tomerfiliba-org/rpyc

extra:
  recipe-maintainers:
    - mtsolmn
    - comrumino
    - jacobfeder
