{% set name = "rpyc" %}
{% set version = "5.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tomerfiliba-org/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b93f4cd81a2e592d57fbc6e1673a4bf9c84e6fb1fe0b5f92bef9c57727998a32

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - hatchling
  run:
    - python >=3.6
    - plumbum

test:
  imports:
    - rpyc
    - rpyc.core
    - rpyc.lib
    - rpyc.utils
  commands:
    - pip check
    - rpyc_classic --help
    - rpyc_registry --help
    - rpyc_classic.py --help
    - rpyc_registry.py --help
  requires:
    - pip

about:
  home: https://github.com/tomerfiliba-org/rpyc
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Transparent, Symmetric Distributed Computing

  description: |
    RPyC (pronounced like are-pie-see), or Remote Python Call, is a
    transparent library for symmetrical remote procedure calls,
    clustering, and distributed-computing. RPyC makes use of
    object-proxying, a technique that employs python's dynamic nature, to
    overcome the physical boundaries between processes and computers, so
    that remote objects can be manipulated as if they were local.
  doc_url: https://rpyc.readthedocs.io/
  dev_url: https://github.com/tomerfiliba-org/rpyc

extra:
  recipe-maintainers:
    - mtsolmn
    - comrumino
    - jacobfeder
